name: flow
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  go_router: ^15.1.1
  responsive_framework: ^1.5.1
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  firebase_storage: ^12.4.5
  cloud_firestore: ^5.6.7
  firebase_app_check: ^0.3.2+5
  google_sign_in: ^6.3.0
  flutter_side_menu: ^0.5.41
  provider: ^6.1.5
  shared_preferences: ^2.5.3
  iconly: ^1.0.1
  intl: ^0.19.0
  image_picker: ^1.1.2
  file_picker: ^10.1.9
  image_cropper: ^9.1.0
  supabase_flutter: ^2.9.0
  mime: ^2.0.0
  http: ^1.4.0
  # kanban_board: ^1.0.0+1
  kanban_board: ^1.0.0+2
  appflowy_board: ^0.1.2
  uuid:
  flutter_colorpicker: ^1.1.0
  firebase_messaging: ^15.2.6
  flutter_local_notifications: ^17.0.0
  flutter_launcher_icons: ^0.14.3
  # uni_links: ^0.5.1



  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/image/logo/logoFlowSecond.png"
  min_sdk_android: 21 
  web:
    generate: true
    image_path: "assets/image/logo/logoFlowSecond.png"
    background_color: "#38BB5A"
    theme_color: "#38BB5A"
  windows:
    generate: true
    image_path: "assets/image/logo/logoFlowSecond.png"
    icon_size: 48 
  macos:
    generate: true
    image_path: "assets/image/logo/logoFlowSecond.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/image/
    - assets/image/logo/
    - assets/image/logo/logoff.png
    - assets/fonts/San Francisco Pro Text/

  fonts:
    - family: SFProText
      fonts:
        - asset: assets/fonts/San Francisco Pro Text/SFProText-Light.ttf
          weight: 300
        - asset: assets/fonts/San Francisco Pro Text/SFProText-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/San Francisco Pro Text/SFProText-Regular.ttf
          weight: 400
        - asset: assets/fonts/San Francisco Pro Text/SFProText-RegularItalic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/San Francisco Pro Text/SFProText-Medium.ttf
          weight: 500
        - asset: assets/fonts/San Francisco Pro Text/SFProText-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/San Francisco Pro Text/SFProText-Semibold.ttf
          weight: 600
        - asset: assets/fonts/San Francisco Pro Text/SFProText-SemiboldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/San Francisco Pro Text/SFProText-Bold.ttf
          weight: 700
        - asset: assets/fonts/San Francisco Pro Text/SFProText-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/San Francisco Pro Text/SFProText-Heavy.ttf
          weight: 800
        - asset: assets/fonts/San Francisco Pro Text/SFProText-HeavyItalic.ttf
          weight: 800
          style: italic
flutter_intl:
  enabled: true
