// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoa1-AjGMeLwtW99-4wtDDSzAq4l3SjMY',
    appId: '1:893306967954:web:5a136be308c956a195934b',
    messagingSenderId: '893306967954',
    projectId: 'flow-ed624',
    authDomain: 'flow-ed624.firebaseapp.com',
    storageBucket: 'flow-ed624.firebasestorage.app',
    measurementId: 'G-ZVMH0XLKEN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfdD7jTKZffXU1hCZf11S1bnKvjrHikB4',
    appId: '1:893306967954:android:dde39b6b1859c31095934b',
    messagingSenderId: '893306967954',
    projectId: 'flow-ed624',
    storageBucket: 'flow-ed624.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_m4H_3ZikbYL5j-a0ID7xsAVIktLLJQM',
    appId: '1:893306967954:ios:4e8dc74183283f0d95934b',
    messagingSenderId: '893306967954',
    projectId: 'flow-ed624',
    storageBucket: 'flow-ed624.firebasestorage.app',
    iosBundleId: 'com.flow.flow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_m4H_3ZikbYL5j-a0ID7xsAVIktLLJQM',
    appId: '1:893306967954:ios:4e8dc74183283f0d95934b',
    messagingSenderId: '893306967954',
    projectId: 'flow-ed624',
    storageBucket: 'flow-ed624.firebasestorage.app',
    iosBundleId: 'com.flow.flow',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAoa1-AjGMeLwtW99-4wtDDSzAq4l3SjMY',
    appId: '1:893306967954:web:8d712ec517c5bf4395934b',
    messagingSenderId: '893306967954',
    projectId: 'flow-ed624',
    authDomain: 'flow-ed624.firebaseapp.com',
    storageBucket: 'flow-ed624.firebasestorage.app',
    measurementId: 'G-45PRQEPWP4',
  );
}
